services:
  api:
    build: .
    restart: always
    command: >
      sh -c "python manage.py collectstatic --no-input &&
                   python manage.py migrate &&
                   python manage.py test &&
                   gunicorn MathematicalService.wsgi:application --reload --log-level INFO --bind 0.0.0.0:$API_PORT"
    volumes:
      - .:/app/
    ports:
      - 80:8000
    env_file:
      - .env.dev
    depends_on:
      - cache
  prometheus:
    image: prom/prometheus:v2.14.0
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - $PROMETHEUS_PORT:9090
    depends_on:
      - cache
      - api
  grafana:
    image: grafana/grafana:6.5.2
    restart: always
    ports:
      - $GRAFANA_PORT:3000
  redis-exporter:
    image: oliver006/redis_exporter:v1.6.0-alpine
    restart: always
    ports:
      - $REDIS_EXPORTER_PORT:9121
    command:
      - "--redis.addr=redis://${REDIS_URL}:${REDIS_PORT}"
      - "--redis.password=${REDIS_PASSWORD}"
    depends_on:
      - cache
  cache:
    image: redis:6.0.9-alpine
    restart: always
    ports:
      - $REDIS_PORT:6379
    command: >
      sh -c "redis-server --save 20 1 --loglevel WARNING --requirepass ${REDIS_PASSWORD}"
    env_file:
      - .env.dev
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
  prometheus:
    driver: local

