services:
  api:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
                   python manage.py migrate &&
                   gunicorn MathematicalService.wsgi:application --reload --log-level INFO --bind 0.0.0.0:8000"
    volumes:
      - .:/app/
    ports:
      - 8000:8000
    env_file:
      - .env.dev

