version: '3.6'
services:
 prometheus:
  image: prom/prometheus:v2.14.0
  volumes:
   - ./prometheus/:/etc/prometheus/
  command:
   - '--config.file=/etc/prometheus/prometheus.yaml'
  ports:
   - "9090:9090"
 grafana:
  image: grafana/grafana:6.5.2
  ports:
   - "3060:3000"
 redis-exporter:
  image: oliver006/redis_exporter:v1.6.0-alpine
  ports:
   - 9121:9121
  command:
   - "--redis.addr=redis://${REDIS_URL}"
   - "--redis.password=${REDIS_PASSWORD}"

 cache:
   image: redis:6.2-alpine
   restart: always
   ports:
    - "6379:6379"
   command: >
    sh -c "redis-server --save 20 1 --loglevel WARNING --requirepass ${REDIS_PASSWORD}"
   env_file:
    - .env.dev
   volumes:
    - cache:/data
volumes:
  cache:
    driver: local
