global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: monitoring
    metrics_path: /metrics
    static_configs:
    - targets:
        - host.docker.internal


  - job_name: redis_monitor
    metrics_path: /metrics
    static_configs:
    - targets:
        - redis-exporter:9121